[build]
  publish = "/"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
